coingecko_api_url: https://api.coingecko.com/api/v3
db_name: tomodex
env: dev
log_level: DEBUG
error_file: config/errors.yaml
tomochain:
  exchange_address: coinsebaseaddress
  exchange_contract_address: exchangesmartcontract
  lending_contract_address: lendingsmartcontract
  http_url: http://localhost:8545
  ws_url: ws://localhost:8546
jwt_signing_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
jwt_verification_key: QfCAH04Cob7b71QCqy738vw5XGSnFZ9d
logs:
  engine: ./engine.log
  main: ./main.log
  operator: ./operator.log
mongo_url: localhost:27017
rabbitmq_url: amqp://guest:guest@localhost:5672/
server_port: 8080
simulated: false
supported_currencies: ETH,TOMO,BTC,USDT
tick_duration:
  day:
  - 1
  hour:
  - 1
  - 4
  - 12
  min:
  - 1
  - 5
  - 15
  - 30
  month:
  - 1
  - 3
  - 6
  - 9
  week:
  - 1
  year:
  - 1